#!/bin/bash

backup() {
  local source="$1"
  local target="${2}_$(date +'%s')"

  echo "Moving [$source] to [$target]..."
  mv "$source" "$target"
}

link() {
  local source="$1"
  local target="$2"

  echo "Symlinking [$source] to [$target]..."
  ln -s "$source" "$target"
}

local source="$(realpath "$1")"
local target="$2"
local bak="${3:-${2}.bak}"

if [[ -e "$target" || -L "$target" ]]; then
  if [[ "$(readlink -nm "$target")" == "$source" ]]; then
    echo "[$target] is already linked to version controlled version [$source]."
  else
    echo "[$target] already exists but doesn't link to [$source]."
    backup "$target" "$bak"
    link "$source" "$target"
  fi
  exit
fi

target_dir="$(dirname "$target")"
if [[ ! -e "$target_dir" ]]; then
  echo "Target parent dir [$target_dir] does not exist. Creating..."
  mkdir -p "$target_dir"
fi

link "$source" "$target"
